### ISSUE TITLE
Add Example of Overriding Node/NPM Versions 

### ISSUE THREAD

**Issue by andrejhronco** [Cycling74/n4m-examples#15]
Since N4M uses node v8.11.3, it would be useful to see how we can use more recent versions of node / npm.

**Comment by fde31** [comment]
We are currently testing and ensuring full functionality with Node 10.13.0 LTS. In general we are planning to stay close with the Node LTS release schedule (https://github.com/nodejs/Release#release-schedule).

Apart from that, I agree it might be good to showcase how one can point node.script to use your local Node and NPM install instead of the bundled one. However, there might be some tweaking necessary on our side to make that a bit more streamlined

Thanks

**Comment by fde31** [comment]
@AndrejHronco I moved this issue to the core-examples repository, which seems more appropriate. You can find the issue here Cycling74/n4m-core-examples#8
