### ISSUE TITLE
Content Organization

### ISSUE THREAD

**Issue by fde31** [Cycling74/n4m-examples#9]
Came up in a chat with @catarak 
We could investigate a TOC, ad banners/intros to READMEs explaining the key usage/what to learn from the specific example.

Also a section for "bigger" projects/external resources seems worthwhile in order to not limit us to maintain everything within the same repo.

**Comment by catarak** [comment]
Turning this into some action items:
- [ ] Investigate ToC (Table of Contents) generation
- [ ] update current examples with more descriptive descriptions, add key usage and what you will learn from looking at a specific example
- [ ] Add step to adding an example guide that outlines how to write a good description for an example
- [ ] Differentiate between basic examples and intermediate/advanced examples
- [ ] Add option in guide to link to example in other GitHub repository rather than copying it to this repo

**Comment by starakaj** [comment]
These sound _groovy_ to me, thanks for chatting guys.

**Comment by fde31** [comment]
closing this has been tackled with the split of the repos
